@startuml Coverage Transformer

    class CoverageCollector{
        - Map<String, CoverageData> finalInfo
        + collect( String className, String methodName, String mDesc, int line)
    }

    class CoverageTransformer{
        - Map<String, CoverageData> finalInfo
        - String projectName
        + @override transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain,
                            byte[] classfileBuffer)
        + passOne(byte[] classByte, ClassData classData, String name)
        + passTwo(byte[] classByte, String name)
    }
@enduml
