@startuml
skinparam wrapwidth 200
package "req [Package] Feedback [requirement diagram]" {

    stereotype "Status" as status <<Requirement>> {
        overview = A developer or team lead are interested to know if the code reviewer has requested more changes or
        approved the code review.
    }

    stereotype "Priority levels" as levels <<Requirement>> {
        overview = While reviewing code, once the code reviewer has identified a infrigment he will categorize in
        levels.

        Top level rules infringments would make the reviewer reject the implementation.
    }

    stereotype "Code commentaries" as commentaries <<Requirement>> {
        overview = The code reviewer ensures code reviewing rules are being followed and writes comment on the specific
        file and line where a rule is not being followed.

        A file could have commentaries. It should be easy to know from which line is the commentary.

        CS-005 [SP-0] : As a developer I want to have comments on my PR
    }
    commentaries <.. levels: <<deriveReqt>>

    stereotype "Code review feedback" as feedback <<Requirement>> {
        overview = Once the code review is finished, the results should be published. Developer and sometimes team lead
        would review those.

        The developer takes the feedback. He will implement those observatiosn that he agrees with and debate those that
        he doesn't.
    }
    feedback +-- commentaries
    feedback +-- status
}
@enduml
    stereotype "" as <<Requirement>> {
        overview =
    }
